export const SET_PRODUCT_LIST = 'SET_PRODUCT_LIST';
export const EXPAND_PRODUCT_LIST = 'EXPAND_PRODUCT_LIST';

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
